language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: heroku
  api_key:
    secure: a0693624-fb05-449b-97a7-c86d4c4b8453
